<template>
  <div>
    <h1>Welcome to my Nuxt page!</h1>
    <p>This is a sample Nuxt page generated by GitHub Copilot.</p>
  </div>
</template>

<script script>
// Set a different layout for this page
definePageMeta({
  layout: 'product'
})
</script>
