<template>
  <div>
    <h1>Welcome to my Nuxt page!</h1>
    <p>This is a sample Nuxt page generated by GitHub Copilot.</p>
  </div>
</template>

<script>
export default {
  name: 'IndexPage'
}
</script>

<style>
h1 {
  font-size: 3rem;
  text-align: center;
  margin-top: 2rem;
}

p {
  font-size: 1.5rem;
  text-align: center;
  margin-top: 1rem;
}
</style>
